	name: CI

	on: [push]

	jobs:
	deploy:
		if: github.ref == 'refs/heads/main'
		runs-on: [ubuntu-latest]
		steps:
		- uses: actions/checkout@v1
		- name: Push to server
			uses: appleboy/ssh-action@master
			with:
			host: ${{ secrets.SERVER_IP }}
			port: ${{ secrets.SERVER_PORT }}
			username: ${{ secrets.SERVER_USERNAME }}
			key: ${{ secrets.SERVER_KEY }}
			script: cd ${{ secrets.PROJECT_PATH }} && git pull && make && mv cv.pdf ${{ secrets.WEB_PATH }}/static/ && make clean && cd ${{ secrets.WEB_PATH }} && git add -A && git commit -m "updated pdf" && git push
